### ISSUE TITLE
colored_box height calculation

### ISSUE THREAD

**Issue by nilcolor** [prawnpdf/prawn-manual_builder#5]
Hello,
I tried to re-use https://github.com/prawnpdf/prawn-manual_builder/blob/1fdbb0beaa1b9d1ddf403640d70907d19c652d60/lib/prawn/manual_builder/example.rb#L328C11-L328C22 code and found that `box_height` calculation gives me smaller values than expected. Especially when text is long.

```ruby
box_height = height_of_formatted(box_text, text_options)

bounding_box([INNER_MARGIN + RHYTHM, cursor], :width => bounds.width - (INNER_MARGIN+RHYTHM)*2) do
  ...
  formatted_text(box_text, text_options)
  ...
end
```

So, after a few attempts, I ended up with following:

```ruby
bounding_box([INNER_MARGIN + RHYTHM, cursor], :width => bounds.width - (INNER_MARGIN+RHYTHM)*2) do
  box_height = height_of_formatted(box_text, text_options)
end

bounding_box([INNER_MARGIN + RHYTHM, cursor], :width => bounds.width - (INNER_MARGIN+RHYTHM)*2) do
  ...
  formatted_text(box_text, text_options)
  ...
end
```
i.e. `height_of_formatted` is also called within `bounding_box` thus providing correct value.
In my case, I call it in a separate block because I also do this
```ruby
bounding_box([INNER_MARGIN + RHYTHM, cursor], :width => bounds.width - (INNER_MARGIN+RHYTHM)*2) do
  box_height = height_of_formatted(box_text, text_options)
end

start_new_page if cursor - box_height - RHYTHM * 2 < 0
```
which is not possible (`start_new_page`) to do inside `bounding_box`.

I have two questions here. Is that empty `bounding_box` may cause any issues? I expect its height to be zero, right?
And, is it worth to update `#colored_box` helper here?

**Comment by pointlessone** [comment]
Thank you.

1. TBH, I don't know. Intuitively it shouldn't but realistically it might. It's height is zero but there might be other effect.
2. It's probably worth updating it but no need to spend your time on it right now. I'm actually working on the Manual builder. I will look into it.

**Comment by nilcolor** [comment]
I'll close this issue then. And will hope there will be no side-effects as I'm going to use this trick :) I need that height :)
